language: java
dist: trusty

jdk:
  - openjdk8

sudo: required
services:
  - docker

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - docker pull axiom/rsync-server
  - echo -e "Host localhost\n\tStrictHostKeyChecking no\n" >> $HOME/.ssh/config
  - echo 'localhost ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMaFQFXjCQRbvc8XQpz3DZHF/spSHqqpfNgiFp+KUHtaysaHn2kpx2dpurkx7TvM9bxBgxoNj4WNwce4UqwJgSo=' >> $HOME/.ssh/known_hosts

jobs:
  include:
    - stage: test
      script:
        - chmod 0600 $TRAVIS_BUILD_DIR/vendor/vendor-ios/src/test/resources/fixtures/derived-data-manager/test_rsa
        - ./gradlew clean test jacocoTestReport integrationTest
        - bash <(curl -s https://codecov.io/bash)
    - stage: detekt
      script: ./gradlew clean detektCheck
    - stage: deploy
      script: skip
      deploy:
        - provider: script
          script: bash .buildsystem/deploy-sonatype.sh
          on:
            branch: develop
        - provider: script
          script: bash .buildsystem/deploy-sonatype.sh
          on:
            tags: true
        # - provider: script
        #   script: bash .buildsystem/deploy-github.sh
        #   on:
        #     tags: true
    - stage: deploy-cli
      script: ./gradlew :cli:assembleDist -PreleaseMode=RELEASE
      before_deploy:
        - rm -f cli/build/distributions/marathon-*-SNAPSHOT.zip || true
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: "cli/build/distributions/marathon-*.zip"
        file_glob: "true"
        skip_cleanup: true
        on:
          repo: Malinskiy/marathon
          tags: true
