language: android

jdk:
  - oraclejdk8

sudo: required
services:
  - docker

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

before_install:
  - docker pull axiom/rsync-server
  - echo -e "Host localhost\n\tStrictHostKeyChecking no\n" >> $HOME/.ssh/config
  - echo 'localhost ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMaFQFXjCQRbvc8XQpz3DZHF/spSHqqpfNgiFp+KUHtaysaHn2kpx2dpurkx7TvM9bxBgxoNj4WNwce4UqwJgSo=' >> $HOME/.ssh/known_hosts

env:
 global:
 - ANDROID_API=26
 - ANDROID_BUILD_TOOLS=26.0.2

android:
  components:
    - tools
    - tools # Running this twice get's the latest build tools (https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI)
    - platform-tools
    - android-${ANDROID_API}
    - build-tools-${ANDROID_BUILD_TOOLS}
    - extra

jobs:
  include:
  - stage: test
    script:
    - chmod 0600 $TRAVIS_BUILD_DIR/vendor-ios/src/test/resources/fixtures/derived-data-manager/test_rsa
    - ./gradlew clean test
  - stage: detekt
    script: ./gradlew clean detektCheck
  - stage: deploy
    script: skip
    deploy:
    - provider: script
      script: bash .buildsystem/deploy.sh
      on:
        branch: develop
    - provider: script
      script: bash .buildsystem/deploy.sh
      on:
        tags: true
  - stage: deploy-cli
    script: ./gradlew :cli:assembleDist
    deploy:
      provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      file: "cli/build/distributions/marathon-*.zip"
      file_glob: "true"
      skip_cleanup: true
      on:
        repo: Malinskiy/marathon
        tags: true
